version: "3.8"
services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    build:
      context: .
      dockerfile: ./docker/dockerfiles/nginx.Dockerfile
      target: dev
    restart: unless-stopped
    volumes:
      - ./src:/usr/src
    ports:
      - "${DOCKER_APP_PORT}:80"
    depends_on:
      - php

  php:
    container_name: ${COMPOSE_PROJECT_NAME}-php
    build:
      args:
        user: ${DOCKER_USER}
        uid: 1000
      context: .
      dockerfile: ./docker/dockerfiles/php.Dockerfile
      target: dev
    command: sh -c "/usr/./wait-for-it.sh mysql:3306 -t 30 && /usr/./wait-for-it.sh redis:6379 -t 30 && cd /usr/src/ && composer install --no-scripts && /usr/./update.sh && php-fpm"
    restart: unless-stopped
    volumes:
      - ./src:/usr/src
      - ./docker/deployment/config/php-fpm/php-dev.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
      - redis

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    build:
      args:
        password: ${DB_PASSWORD}
      context: .
      dockerfile: ./docker/dockerfiles/mysql.Dockerfile
    restart: unless-stopped
    volumes:
      - ./docker/volumes/mysqldata:/var/lib/mysql
    ports:
      - "${DOCKER_DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: redis:7.0.11-alpine
    restart: unless-stopped
    volumes:
      - ./docker/volumes/redisdata:/data
    ports:
      - "${DOCKER_REDIS_PORT}:6379"

  laravel-prod-npm:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/frontend.Dockerfile
    volumes:
      - ./src:/usr/src
      - ./.env:/usr/src/.env
    working_dir: /usr/src
    profiles: ["npm"]
    entrypoint: ['npm']
    ports:
      - "${DOCKER_VITE_PORT}:5173"

  scheduler:
    container_name: ${COMPOSE_PROJECT_NAME}-scheduler
    build:
      args:
        user: ${DOCKER_USER}
        uid: 1000
      context: .
      dockerfile: ./docker/dockerfiles/php.Dockerfile
      target: scheduler
    restart: unless-stopped
    volumes:
      - ./src:/usr/src
    depends_on:
      - php
      - mysql
      - redis

  npm:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/frontend.Dockerfile
    volumes:
      - ./src:/usr/src
    working_dir: /usr/src
    profiles: ["npm"]
    entrypoint: ['npm']
    ports:
      - "${DOCKER_VITE_PORT}:5173"

#  worker:
#    container_name: ${COMPOSE_PROJECT_NAME}-worker
#    build:
#      args:
#        user: ${DOCKER_USER}
#        uid: 1000
#      context: .
#      dockerfile: ./docker/dockerfiles/php.Dockerfile
#      target: worker
#    restart: unless-stopped
#    volumes:
#      - ./src:/usr/src
#    depends_on:
#      - update
#      - mysql
#      - redis

#  proxy:
#    container_name: ${COMPOSE_PROJECT_NAME}-proxy
#    build:
#      context: .
#      dockerfile: ./docker/dockerfiles/proxy.Dockerfile
#      target: local
#    restart: unless-stopped
#    ports:
#      - "${APP_PORT}:80"
#    volumes:
#      - ./docker/deployment/config/proxy.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - nginx