version: "3.8"
services:
  nginx:
    image: ${DOCKER_HUB_USER}/${COMPOSE_PROJECT_NAME}-nginx:${IMAGE_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    restart: unless-stopped
    volumes:
      - type: volume
        source: storage
        target: /usr/src/storage
    ports:
      - "${DOCKER_APP_PORT}:80"
    depends_on:
      - php

  php:
    image: ${DOCKER_HUB_USER}/${COMPOSE_PROJECT_NAME}-php:${IMAGE_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}-php
    command: sh -c "cd /usr && ./wait-for-it.sh mysql:3306 -t 30 && ./wait-for-it.sh redis:6379 -t 30 && /usr/./update.sh && php-fpm"
    restart: unless-stopped
    volumes:
      - ./.env:/usr/src/.env
      - type: volume
        source: storage
        target: /usr/src/storage
    depends_on:
      - mysql
      - redis

  scheduler:
    image: ${DOCKER_HUB_USER}/${COMPOSE_PROJECT_NAME}-scheduler:${IMAGE_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}-scheduler
    restart: unless-stopped
    volumes:
      - ./.env:/usr/src/.env
      - type: volume
        source: storage
        target: /usr/src/storage
    depends_on:
      - php
      - mysql
      - redis

  mysql:
    image: ${DOCKER_HUB_USER}/${COMPOSE_PROJECT_NAME}-mysql:${IMAGE_TAG}
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    restart: unless-stopped
    volumes:
      - type: volume
        source: mysqldata
        target: /var/lib/mysql
    ports:
      - "${DOCKER_DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  redis:
    image: redis:7.0.11-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    restart: unless-stopped
    volumes:
      - type: volume
        source: redisdata
        target: /data
    ports:
      - "${DOCKER_REDIS_PORT}:6379"

volumes:
  storage:
  mysqldata:
  redisdata: