version: "3.8"
services:
  nginx:
    image: ${DOCKER_HUB_USER}/${COMPOSE_PROJECT_NAME}-nginx:${IMAGE_TAG}
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - php

  php:
    image: ${DOCKER_HUB_USER}/${COMPOSE_PROJECT_NAME}-php:${IMAGE_TAG}
    command: sh -c "cd /usr && ./wait-for-it.sh mysql:3306 -t 30 && ./wait-for-it.sh redis:6379 -t 30 && php-fpm"
    restart: unless-stopped
    depends_on:
      - update
      - mysql
      - redis

  mysql:
    image: ${DOCKER_HUB_USER}/${COMPOSE_PROJECT_NAME}-mysql:${IMAGE_TAG}
    restart: unless-stopped
    volumes:
      - ./docker/volumes/mysqldata:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: redis:7.0.11-alpine
    restart: unless-stopped
    volumes:
      - ./docker/volumes/redisdata:/data
    ports:
      - "${REDIS_PORT}:6379"

  update:
    image: ${DOCKER_HUB_USER}/${COMPOSE_PROJECT_NAME}-php:${IMAGE_TAG}
    command: sh -c "cd /usr && ./wait-for-it.sh mysql:3306 -t 30 && ./update.sh"
    restart: "no"
    depends_on:
      - mysql